### PR TITLE
return publicProfileURL with profile info

### PR DESCRIPTION
**Pull request by andrijan**
You already provide everything else you get, so let's add the profile URL as well.

### CODE REVIEW

**Comment by nicolas-goudry** [comment]
Thanks for your kind contribution @andrijan!

**Comment by andrijan** [comment]
You're welcome! When are you planning on publishing?

**Comment by andrijan** [comment]
Any news on publishing this? I really need it :)

**Comment by nicolas-goudry** [comment]
@andrijan I plan to release a minor version by tonight.

Sorry I didn’t noticed your comments earlier as PR is closed!

**Pull request merged**
