### PR TITLE
Added support for optional LoaderComponent

### PR DESCRIPTION
**Pull request by karthikdivi**
Added support for optional LoaderComponent, this will be rendered until the respective SDKs are initialised

### CODE REVIEW

**Comment by jinojacob15** [comment]
@karthikdivi how can i pull the latest code ? by updating npm package ? its still showing version 3.4.14 . Please help

**Comment by karthikdivi** [comment]
> @karthikdivi how can i pull the latest code ? by updating npm package ? its still showing version 3.4.14 . Please help

@jinojacob15 The PR is still open, this need to me merged and released by maintainers

**Comment by deepakaggarwal7** [comment]
Thanks for adding this feature. I'd appreciate if you can also update READ ME.

**Comment by jino-webandcrafts** [comment]
@karthikdivi can u update the READ ME file for further understanding

**Pull request merged**
