### PR TITLE
Return id_token in Google auth response

### PR DESCRIPTION
**Pull request by Nosajool**
Hi Nicolas! Awesome plugin!

I'd like to expose a couple more `authResponse` bits that are required for authenticating with Amazon Cognito. Mainly the `id_token`.

https://developers.google.com/identity/sign-in/web/reference#googleusergetauthresponseincludeauthorizationdata

### CODE REVIEW

**Comment by nicolas-goudry** [comment]
Hi Jason, thanks for your kind contribution!

Can you please merge your branch `google-id-token-with-updated-build` into `google-id-token` so it is added to this PR?

**Comment by Nosajool** [comment]
Done 😄 

There is one additional change in `window.amazon.Login.authorize` which I think should be `amazon` instead of `linkedin`

**Comment by nicolas-goudry** [comment]
Saw this, well spotted ;)

**Comment by nicolas-goudry** [comment]
Wow sorry man I didn’t saw you wanted to merge into `master`… I had to revert.

Can you open a new PR into `develop` please? Sorry again I didn’t spot that earlier.

**Pull request merged**
