### PR TITLE
add types

### PR DESCRIPTION
**Pull request by iwanttobealight**
hello
I add typescript types for your amazing package ^^

### CODE REVIEW

**Comment by deepakaggarwal7** [comment]
Hi Daria,

Thanks for making this contribution and for your kind words. I've two queries regarding your PR:
#1 What purpose does this serves as rest of the project doesn't have a typescript footprint
#2 Does it causes an additional npm dependency (It's better open sources remain as lean as possible)
If you could help me with these, I'd be more than happy to merge it and release as next version.
thanks again! I owe the success of this library to people like you :)

**Comment by whizsid** [comment]
@deepakaggarwal7  Can you merge it. ThiPR is not getting any issues to your project. I have also tested it. I can not use this great library to my typescript project if you didn't merge it.

**Comment by DomainBender** [comment]
@deepakaggarwal7 
1- It enables this library to be used by projects with typescript.
2- The only dependency is a procedural one, you will have to update the types whenever you change your API, it only happens during a major release since you follow semver.

**Comment by deepakaggarwal7** [comment]
Thanks a lot for this. I've merged and published it. I messed a bit and
published before read.me update. However, I've updated the ReadMe version
thanking you which you should see on git:)

**Pull request merged**
