### PR TITLE
Code/dependency update and linting proposal

### PR DESCRIPTION
**Pull request by nicolas-goudry**
Hi @deepakaggarwal7,

I like your project and would like to contribute to it as I will heavily need it in near future 😄 

So here I propose you a little code update along some dependencies update:
- cleaned code (code style and enhancements)
- split the loaders config to separate files
- remove unused files
- add missing dev dependencies
- add eslint with [standard code style](http://standardjs.com/)
- update to webpack 2

Please tell me your thoughts about this, I saw that in #3 you say you’re planning on continuing the development, so I try my luck 👍

### CODE REVIEW

**Comment by deepakaggarwal7** [comment]
Thanks Nicolas. react-social-login seems to be picking up and I definitely wish to make it better. At high level, all of your commit makes sense. Give me a little time to test and I'll soon revert on your pill request( most likely with a merge).

Thanks for the help! Really Appreciate!

**Comment by deepakaggarwal7** [comment]
Were you able to run Demo.jsx or any of your demo with the changes? I'm getting error
image

**Comment by nicolas-goudry** [comment]
I didn't run the repo demo files, I npm linked the module on my machine and I'm (still) using it on my main project with no problems at all (I only have FB at the time but will add LinkedIn soon)

**Comment by nicolas-goudry** [comment]
@deepakaggarwal7: Ok, I fixed it, I didn't push all my latest code, let me create a new PR to resolve this, ok?

**Pull request merged**
