### PR TITLE
Adds support for passing scopes

### PR DESCRIPTION
**Pull request by kamranahmedse**
With the PR merged you can pass an array of scopes to the component which will be sent to the provider in case any extra permissions are needed.

Also, I changed the function params to be destructured object so that you don't have to remember the order plus if the number of arguments grow it doesn't create a mess.

### CODE REVIEW

**Comment by kamranahmedse** [comment]
PS, I added the support for google only. If it gets merged, I will work on the others.

**Comment by nicolas-goudry** [comment]
Thanks for your kind contribution ! I will have a look on this tomorrow 😉

**Comment by kamranahmedse** [comment]
@nicolas-goudry thanks

**Comment by kamranahmedse** [comment]
@nicolas-goudry done

**Pull request merged**
