### PR TITLE
Can't login after Google Auth popup closed. Errors "popup_closed_by_user", "Fetching user"

### PR DESCRIPTION
**Pull request by alekseykravetz**
added onLoginFailure logic at sdk.login canceled

issue #109

### CODE REVIEW

**Comment by alekseykravetz** [comment]
issue: #107

**Comment by bernardorubin** [comment]
We really need this merged!

**Comment by mmclafferty** [comment]
This has been an issue for a long time now and I am about to drop this module because of this issue. Is there going to be any progress on getting this through?

**Review by uvtech3012 — APPROVED** [review]
looks good

**Review by deepakaggarwal7 — APPROVED** [review]

**Pull request merged**
